### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by vbisbest** [payloadbox/xss-payload-list#10]
Are these payloads expected to be encoded before sending?  For example, the request will fail if you do not encode spaces in the query string.  However encoding the query string will change the other values that may be required for the attack to work.   Thoughts?  Thank you.

**Comment by ismailtasdelen** [comment]
Hi @vbisbest,

Encoding is required for each payload. You know, this can vary according to the web application test to bypass things.

Thanks issue :+1:

**Comment by ismailtasdelen** [comment]
If there is a problem, you can open this topic again.

**Comment by vbisbest** [comment]
I am not sure about encoding the whole payload.  For instance this simple payload:
&lt;IMG SRC=\"javascript&#058;alert('XSS')\"

You need to encode this payload because of the spaces, however doing so, modifies the &lt; and encodes that (turns into %26lt%3B%0A).  Thoughts.

**Comment by ismailtasdelen** [comment]
You have to do the necessary encoding processes.
